
data_source: http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv

artifacts: 
  binder_dir: binder_files
binder_rules:
  templates-1: 
      name: "Aircraft Policy - ABC Form"
      policy_names: "Aircraft Policy - ABC Form"
      location: "Newyork"
  template-2:
      name: "Aircraft policy Broad Covg(original)"
      policy_names: "Aircraft Policy - Broad Coverage Endorsement,Aircraft Policy – Broad Coverage Form"
      location: "Newyork,NY,AK,Arkansa"
      tags: "Broad Coverage"
      additional_coverage:
          - "Airworthiness Certificate"
          - "Automatic Insurance for Increased Insured Value"
          - "Baggage and Personal Effects"
          - "Hanger and Contents Coverage"
          - "Premises Liability"
          - "Emergency or Unexpected Landing"
          - "Extra Expense for Renting Substitute Aircraft"
          - "Extra Expense for Temporaray Replacement Aircraft Parts"
          - "Hangarkeeper's Liability"
          - "Host Liquor Liability"
          - "Mobile Equipment Liability"
          - "Spare Parts"
          - "Territory Revision"
          - "Premises Medical Coverage"
          - "Products Liability, Sale of Aircraft, etc"
          - "Runway or Aircraft Foaming"
          - "Search and Rescue"
          - "Trip Interruption Expense"
          - "Unearned Premium Insurance"
  template-3:
      name: "Aircraft Policy - Broad Coverage"
      policy_names: "Aircraft Insurance Policy - Broad Coverage Endorsement,Aircraft Policy – Broad Coverage Form"
      location: "Newyork,NY,AK,Arkansa"
      tags: "Broad Coverage"
  template-4:
      name: "Aircraft Policy (Individual)"
      policy_names: "Aircraft Policy – Standard Form,Aircraft Policy,Aircaft Insurance Policy"
      tags: "Individual"
  template-5:
      name: "Aircraft policy (broad)"
      policy_names: "Aircraft Policy – Standard Form,Aircraft Policy,Aircaft Insurance Policy"
      tags: "Broad Coverage"
      additional_coverage:
          - "Airworthiness Certificate"
          - "Automatic Insurance for Increased Insured Value"
          - "Baggage and Personal Effects"
          - "Hanger and Contents Coverage"
          - "Premises Liability"
          - "Emergency or Unexpected Landing"
          - "Extra Expense for Renting Substitute Aircraft"
          - "Extra Expense for Temporaray Replacement Aircraft Parts"
          - "Hangarkeeper's Liability"
          - "Host Liquor Liability"
          - "Mobile Equipment Liability"
          - "Spare Parts"
          - "Territory Revision"
          - "Premises Medical Coverage"
          - "Products Liability, Sale of Aircraft, etc"
          - "Runway or Aircraft Foaming"
          - "Search and Rescue"
          - "Trip Interruption Expense"
          - "Unearned Premium Insurance"
         

    