
artifacts: 
    binder_dir: binder_files
binder_rules:
    templates-1: 
      name: "Aircraft policy (broad)"
      policy_names: "Aircraft Policy – Standard Form,Aircraft Policy,Aircaft Insurance Policy"
      location: ""
      tags: "Broad Coverage"
      condition_to_pass: "greater_than_equal_to"
      threshold: "7"
      additional_coverage:
          - "Airworthiness Certificate"
          - "Automatic Insurance for Increased Insured Value"
          - "Baggage and Personal Effects"
          - "Hanger and Contents Coverage"
          - "Premises Liability"
          - "Emergency or Unexpected Landing"
          - "Extra Expense for Renting Substitute Aircraft"
          - "Extra Expense for Temporaray Replacement Aircraft Parts"
          - "Hangarkeeper's Liability"
          - "Host Liquor Liability"
          - "Mobile Equipment Liability"
          - "Spare Parts"
          - "Territory Revision"
          - "Premises Medical Coverage"
          - "Products Liability, Sale of Aircraft, etc"
          - "Runway or Aircraft Foaming"
          - "Search and Rescue"
          - "Trip Interruption Expense"
          - "Unearned Premium Insurance"
    template-2:
      name: "Aircraft policy Broad Covg(original)"
      policy_names: "Aircraft Policy – Standard Form,Aircraft Policy,Aircaft Insurance Policy"
      location: "NY/Newyork,AK/Arkansa"
      tags: "Broad Coverage"
      condition_to_pass: "greater_than_equal_to"
      threshold: "10"
      additional_coverage:
          - "Airworthiness Certificate"
          - "Automatic Insurance for Increased Insured Value"
          - "Baggage and Personal Effects"
          - "Hanger and Contents Coverage"
          - "Premises Liability"
          - "Emergency or Unexpected Landing"
          - "Extra Expense for Renting Substitute Aircraft"
          - "Extra Expense for Temporaray Replacement Aircraft Parts"
          - "Hangarkeeper's Liability"
          - "Host Liquor Liability"
          - "Mobile Equipment Liability"
          - "Spare Parts"
          - "Territory Revision"
          - "Premises Medical Coverage"
          - "Products Liability, Sale of Aircraft, etc"
          - "Runway or Aircraft Foaming"
          - "Search and Rescue"
          - "Trip Interruption Expense"
          - "Unearned Premium Insurance"
    template-3:
      name: "Aircraft Policy - Broad Coverage"
      policy_names: "Aircraft Policy – Broad Coverage Form,Aircraft Policy – Broad Coverage Endorsement"
      location: ""
      tags: "Broad Coverage"
      condition_to_pass: ""
      threshold: "1"
      additional_coverage:
          - "Broad Coverage Endorsement"
    template-4:
      name: "Aircraft policy Individual Covg(original)"
      policy_names: "Aircraft Policy – Standard Form,Aircraft Policy,Aircaft Insurance Policy"
      location: "NY/Newyork,AK/Arkansa"
      tags: "Individual"
    template-5:
      name: "Aircraft Policy (Individual)"
      policy_names: "Aircraft Policy – Standard Form,Aircraft Policy,Aircaft Insurance Policy"
      location: ""
      tags: "Individual"